### ISSUE TITLE
一些错误

### ISSUE THREAD

**Issue by Uevo001** [entr0pia/magisk_patch#3]
最新v26.1版本
在archlinux执行boot_patch.sh：

zsh: ./boot_patch.sh: bad interpreter: /system/bin/sh: 没有那个文件或目录
./util_functions.sh:行43: getprop：未找到命令
./util_functions.sh:行43: getprop：未找到命令
./util_functions.sh:行16: /proc/self/fd/: 是一个目录
./boot_patch.sh:行89: ./magiskboot：无法执行二进制文件: 可执行文件格式错误
./util_functions.sh:行16: /proc/self/fd/: 是一个目录
./util_functions.sh:行16: /proc/self/fd/: 是一个目录

**Comment by entr0pia** [comment]
在`adb shell`里面运行, 不需要root权限
