### ISSUE TITLE
inaccessible or not found

### ISSUE THREAD

**Issue by Ayudaroot** [entr0pia/magisk_patch#4]
Hi, how to solve that:
a20s:/sdcard/download/magisk_patch $ boot_patch.sh boot.img
**/system/bin/sh: boot_patch.sh: inaccessible or not found**

**Comment by entr0pia** [comment]
1. `sh <path>boot_patch.sh`
2. Check if the linebreak is `LF`

**Comment by Ayudaroot** [comment]
`sh <path>boot_patch.sh
Check if the linebreak is LF`

Solved, thanks u !
